language: node_js
node_js:
  - 'node'

branches:
  only:
    - master

services:
  - xvfb

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

before_script:
  - npm install -g @angular/cli@8.1.1

install:
  - npm install

script:
  - ng test lc-modal-lib --watch=false
